Ext.define('NereaML.locale.es.Labels', {
	override: 'NereaML.view.Labels',
	buttonAlta: 'Add',
	buttonEditar: 'Edit',
	buttonBorrar: 'Delete',
	error:'Error',
	desErrorServer:'An error has occurred on the server.',
	informacion:'information',
	desInfSelReg:'You must select a record',
	desInfAddUser:'You must add a user',
	desInfoEliminar:'¿Do you want to delete the record?',
    titleTablaPersonal: 'List of Users',
    Nombre:'Name',
    Email:'Email',
    Telefono:'Phone',
    tab:{
    	user:'Users',
    	edit:'Form',
    	detalle:'Profile'
    },
    fecAlta:'Discharge Date',
    fecModificacion:'Modification Date',
    saldo:'Balance',
    progressbarUp:'...Updating...',
    progressbar_100:'...Finished...',
    login:'Login',
    Password:'Password',
    InciarSesion:'Sign into your account',
    CrearCuenta:'Create Account',
    Registrar:'Register'
});