Ext.define('NereaML.locale.es.Labels', {
	override: 'NereaML.view.Labels',
	buttonAlta: 'Añadir',
	buttonEditar: 'Editar',
	buttonBorrar: 'Borrar',
	error:'Error',
	desErrorServer:'Se ha producido un error en el servidor.',
	informacion:'Información',
	desInfSelReg:'Debe selecionar un registro',
	desInfAddUser:'Debe añadir un usuario',
	desInfoEliminar:'¿Desea eliminar el registro?',
    titleTablaPersonal: 'Listado de Usuarios',
    Nombre:'Nombre',
    Email:'Email',
    Telefono:'Teléfono',
    tab:{
    	user:'Usuarios',
    	edit:'Formulario',
    	detalle:'Perfil'
    },
    fecAlta:'Fecha Alta',
    fecModificacion:'Fecha Modificación',
    saldo:'Saldo',
    progressbarUp:'...Subiendo...',
    progressbar_100:'...Finalizado...',
    login:'Iniciar sesión',
    Password:'Contraseña',
    InciarSesion:'Iniciar sesión en su cuenta',
    CrearCuenta:'Crear cuenta',
    Registrar:'Registrar'
});